/**
 * Server example with encryption (Basic256Sha256 Sign & Encrypt).
 *
 * This example demonstrates:
 * - Security Policy: Basic256Sha256
 * - Authentication: X.509 Certificate-based
 * - SecurityMode: SignAndEncrypt
 *
 * The server generates its own certificate and loads trusted client certificates from
 * the "pki/trusted_clients" directory. Client certificates can be copied there manually
 * or will be loaded automatically if generated by the client_encryption example.
 *
 * Directory structure:
 *   pki/
 *     server/
 *       server_cert.der    - Server's certificate (generated)
 *       server_key.pem     - Server's private key (generated)
 *     trusted_clients/
 *       *.der              - Trusted client certificates (loaded)
 *
 * @note Requires open62541 built with encryption (UA_ENABLE_ENCRYPTION) and certificate
 *       generation support (open62541 >= v1.3 with OpenSSL/LibreSSL).
 */

#include <filesystem>
#include <fstream>
#include <iostream>
#include <vector>

#include <open62541pp/config.hpp>

#if defined(UA_ENABLE_ENCRYPTION) && UAPP_HAS_CREATE_CERTIFICATE

#include <open62541pp/node.hpp>
#include <open62541pp/plugin/accesscontrol_default.hpp>
#include <open62541pp/plugin/create_certificate.hpp>
#include <open62541pp/server.hpp>

namespace fs = std::filesystem;

// Helper to write a ByteString to a file
void writeFile(const fs::path& path, const opcua::ByteString& data) {
    std::ofstream file(path, std::ios::binary);
    if (!file) {
        throw std::runtime_error("Failed to open file for writing: " + path.string());
    }
    const auto* ptr = reinterpret_cast<const char*>(data.data());  // NOLINT
    file.write(ptr, static_cast<std::streamsize>(data.size()));
    if (!file) {
        throw std::runtime_error("Failed to write file: " + path.string());
    }
}

// Helper to read a ByteString from a file
opcua::ByteString readFile(const fs::path& path) {
    std::ifstream file(path, std::ios::binary | std::ios::ate);
    if (!file) {
        throw std::runtime_error("Failed to open file for reading: " + path.string());
    }
    const auto size = file.tellg();
    file.seekg(0, std::ios::beg);
    std::vector<uint8_t> buffer(static_cast<size_t>(size));
    file.read(reinterpret_cast<char*>(buffer.data()), size);  // NOLINT
    if (!file) {
        throw std::runtime_error("Failed to read file: " + path.string());
    }
    return opcua::ByteString{buffer.begin(), buffer.end()};
}

// Load all .der certificate files from a directory
std::vector<opcua::ByteString> loadCertificatesFromDirectory(const fs::path& dir) {
    std::vector<opcua::ByteString> certificates;
    if (!fs::exists(dir)) {
        return certificates;
    }
    for (const auto& entry : fs::directory_iterator(dir)) {
        if (entry.is_regular_file() && entry.path().extension() == ".der") {
            std::cout << "  Loading trusted certificate: " << entry.path().filename() << std::endl;
            certificates.push_back(readFile(entry.path()));
        }
    }
    return certificates;
}

int main() {
    const std::string serverApplicationUri = "urn:open62541pp.server.application";

    // Create PKI directory structure
    const fs::path pkiDir = "pki";
    const fs::path serverDir = pkiDir / "server";
    const fs::path trustedClientsDir = pkiDir / "trusted_clients";
    const fs::path serverCertPath = serverDir / "server_cert.der";
    const fs::path serverKeyPath = serverDir / "server_key.pem";

    fs::create_directories(serverDir);
    fs::create_directories(trustedClientsDir);

    opcua::ByteString serverCertificate;
    opcua::ByteString serverPrivateKey;

    // Generate or load server certificate
    if (fs::exists(serverCertPath) && fs::exists(serverKeyPath)) {
        std::cout << "Loading existing server certificate..." << std::endl;
        serverCertificate = readFile(serverCertPath);
        serverPrivateKey = readFile(serverKeyPath);
    } else {
        std::cout << "Generating server certificate..." << std::endl;
        const auto serverCert = opcua::createCertificate(
            {
                opcua::String{"C=DE"},
                opcua::String{"O=open62541pp"},
                opcua::String{"CN=open62541ppServer@localhost"},
            },
            {
                opcua::String{"DNS:localhost"},
                opcua::String{std::string{"URI:"} + serverApplicationUri},
            }
        );
        serverCertificate = serverCert.certificate;
        serverPrivateKey = serverCert.privateKey;

        writeFile(serverCertPath, serverCertificate);
        writeFile(serverKeyPath, serverPrivateKey);
        std::cout << "Server certificate saved to " << serverCertPath << std::endl;
    }

    // Load trusted client certificates from directory
    std::cout << "Loading trusted client certificates from " << trustedClientsDir << "..." << std::endl;
    auto trustedClientCerts = loadCertificatesFromDirectory(trustedClientsDir);
    if (trustedClientCerts.empty()) {
        std::cout << "  No trusted client certificates found." << std::endl;
        std::cout << "  Copy client certificates (.der files) to " << trustedClientsDir << std::endl;
        std::cout << "  Or run client_encryption first to generate and copy its certificate." << std::endl;
    }

    // Create server config with encryption enabled
    // Security policies enabled: None, Basic128Rsa15, Basic256, Basic256Sha256, Aes128_Sha256_RsaOaep
    opcua::ServerConfig config{
        4840,               // Port
        serverCertificate,  // Server certificate (DER)
        serverPrivateKey,   // Server private key (PEM)
        trustedClientCerts, // Trust list - trusted client certificates (DER)
        {},                 // Issuer list - CA certificates (DER)
        {}                  // Revocation list - CRLs (DER)
    };

    config.setApplicationUri(serverApplicationUri);
    config.setApplicationName("open62541pp Secure Server Example");

    // Disable anonymous login - require authentication
    // Allow username/password authentication with a demo user
    opcua::AccessControlDefault accessControl{
        false,  // allowAnonymous = false
        {{opcua::String{"user"}, opcua::String{"password"}}}  // username/password login
    };
    config.setAccessControl(accessControl);

    // Remove anonymous user token policy from all endpoints
    // (The endpoints are pre-configured with anonymous by default)
    auto* nativeConfig = config.handle();
    for (size_t i = 0; i < nativeConfig->endpointsSize; ++i) {
        auto& endpoint = nativeConfig->endpoints[i];
        // Filter out anonymous user identity tokens
        size_t writeIdx = 0;
        for (size_t j = 0; j < endpoint.userIdentityTokensSize; ++j) {
            if (endpoint.userIdentityTokens[j].tokenType != UA_USERTOKENTYPE_ANONYMOUS) {
                if (writeIdx != j) {
                    endpoint.userIdentityTokens[writeIdx] = endpoint.userIdentityTokens[j];
                }
                ++writeIdx;
            }
        }
        endpoint.userIdentityTokensSize = writeIdx;
    }

    opcua::Server server{std::move(config)};

    // Add a sample variable node that clients can read/write
    opcua::Node{server, opcua::ObjectId::ObjectsFolder}.addVariable(
        {1, 1000},
        "SecureVariable",
        opcua::VariableAttributes{}
            .setAccessLevel(opcua::AccessLevel::CurrentRead | opcua::AccessLevel::CurrentWrite)
            .setDataType(opcua::DataTypeId::Int32)
            .setValueRank(opcua::ValueRank::Scalar)
            .setValue(opcua::Variant{42})
    );

    std::cout << std::endl;
    std::cout << "Secure OPC UA Server started at opc.tcp://localhost:4840" << std::endl;
    std::cout << "Anonymous login: DISABLED" << std::endl;
    std::cout << "Authentication: Username/Password (user: 'user', password: 'password')" << std::endl;
    std::cout << "Supported security policies:" << std::endl;
    std::cout << "  - Basic128Rsa15" << std::endl;
    std::cout << "  - Basic256" << std::endl;
    std::cout << "  - Basic256Sha256" << std::endl;
    std::cout << "  - Aes128_Sha256_RsaOaep" << std::endl;
    std::cout << std::endl;
    std::cout << "PKI directories:" << std::endl;
    std::cout << "  - Server certificate: " << fs::absolute(serverCertPath) << std::endl;
    std::cout << "  - Trusted clients:    " << fs::absolute(trustedClientsDir) << std::endl;
    std::cout << std::endl;
    std::cout << "For external clients (UaExpert, python-opcua, etc.):" << std::endl;
    std::cout << "  1. Generate your own certificate with YOUR client's ApplicationUri" << std::endl;
    std::cout << "  2. Copy the certificate (.der) to: " << fs::absolute(trustedClientsDir) << std::endl;
    std::cout << "  3. Restart this server to load the new certificate" << std::endl;
    std::cout << "  Note: The certificate's URI must match the client's ApplicationUri!" << std::endl;
    std::cout << std::endl;
    std::cout << "Server is ready to accept encrypted connections." << std::endl;
    std::cout << "Press Ctrl+C to stop the server." << std::endl;

    server.run();
}

#else

int main() {
    std::cerr
        << "This example requires encryption support.\n"
        << "Please rebuild open62541 and open62541pp with encryption enabled:\n"
        << "  - UA_ENABLE_ENCRYPTION=ON\n"
        << "  - open62541 >= v1.3 with OpenSSL/LibreSSL\n"
        << std::endl;
    return 1;
}

#endif
